import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useConnectWallet } from '@web3-onboard/react'
import { useEffect, useState } from 'react'
import { ethers } from 'ethers'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [{ wallet, connecting }, connect, disconnect] = useConnectWallet()
  const [address, setAddress] = useState<string>('')
  const [provider, setProvider] = useState<ethers.providers.Web3Provider | null>(null)
  const [signer, setSigner] = useState<ethers.Signer | null>(null)

  // updates address, provider, signer based on web3Onboard's wallet
  useEffect(() => {
    setAddress(wallet?.accounts[0].address || "")
    const provider = wallet ? new ethers.providers.Web3Provider(wallet.provider, 'any') : null
    provider ? setProvider(provider) : console.log('ooops, couldnt get provider. provider is', provider)
    const signer = provider?.getSigner() 
    signer ? setSigner(signer) : console.log('oops, couldnt get signer, signer is', signer)
    console.log('address, provider, signer connected')
  }, [wallet])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-center'>
        <h1 className='text-3xl'>App</h1>
        <div className='text-xl'>Welcome to the app</div>
        <button type="button" className='bg-slate-400 rounded-xl p-2 mt-1' disabled={connecting} onClick={() => (wallet ? disconnect(wallet) : connect())}> {connecting ? 'connecting' : wallet ? 'disconnect' : 'connect'} </button>
      </div>
    </>
  )
}
